config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#welcome'

  get 'add_prayer_slot/:time_i', to: 'prayer_slots#add', as: :add_prayer_slot
  resources :prayer_slots, only: [:index]

  get 'time_zone', to: 'pages#time_zone', as: :time_zone
  post 'change_time_zone', to: 'pages#change_time_zone', as: :change_time_zone

end

app/models/daily_notification.rb
class DailyNotification < ActiveRecord::Base
end

app/models/prayer_slot.rb
class PrayerSlot < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prayer_slots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  around_filter :set_time_zone

  # toastr display types are "info, success, warning, error"
  # add flash types to match
  TOASTR_TYPES = [:info, :success, :warning, :error]
  add_flash_types(*TOASTR_TYPES)


  # set user's time_zone per request. default to PT.
  def set_time_zone
    old_time_zone = Time.zone
    if current_user && current_user.time_zone.present?
      Time.zone = current_user.time_zone
    else
      Time.zone = Figaro.env.default_time_zone
    end
    yield
  ensure
    Time.zone = old_time_zone
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    start_626 = DateUtils.mandate_start_date # Mon
    end_626 = DateUtils.mandate_finish_date  # Sat

    @calendar_start_date = DateUtils.calendar_start_date

    # HACK: very dumb logic
    # if c is present, have prev link
    # else have next link
    c = params[:c] == '1'
    if c
      @calendar_start_date = DateUtils.calendar_start_date + 1.week
      @next_link = false
      @prev_link = true
    else
      @next_link = true
      @prev_link = false
    end

    if true #TimeZonePresenter.short_name(Time.zone.now) == 'PST'
      @next_link = false
    end

    @prayer_slot_counts = PrayerSlot.group(:due)
                                    .count
                                    .inject({}) do |item, (k,v)|
                                      item[k.to_i] = v;
                                      item
                                    end

    @owned_prayer_slots = PrayerSlot.where(user: current_user)
                                    .inject({}) do |item, record|
                                      item[record.due.to_i] = true;
                                      item
                                    end
    # inactive when outside 626 prayer schedule or time has passed
    # inactive at beginning
    @inactive_prayer_slots = if start_626.to_i > @calendar_start_date.to_i
                               # build a list
                               {}.tap do |inactive|
                                 i = @calendar_start_date.to_i
                                 loop do
                                   inactive[i] = true
                                   i += 30.minutes.to_i
                                   break if i >= start_626.to_i
                                 end
                               end
                             else
                               {}
                             end
    # inactive at end
    end_date_time_i = @calendar_start_date.to_i + 603000
    inactive_end = if end_date_time_i > end_626.to_i
                     {}.tap do |inactive|
                       i = end_626.to_i + 1
                       loop do
                         inactive[i] = true
                         i += 30.minutes.to_i
                         break if i > end_date_time_i
                       end
                     end
                   else
                     {}
                   end
    @inactive_prayer_slots.merge!(inactive_end)
  end

  def time_zone
    if !user_signed_in?
      redirect_to root_path, flash: { warning: 'You must sign in to do that.' }
    end
  end

  def change_time_zone
    current_user.time_zone = params[:time_zone]
    current_user.save!
    redirect_to time_zone_path, { success: "Time zone set to #{params[:time_zone]}" }
  end
end

app/controllers/prayer_slots_controller.rb
class PrayerSlotsController < ApplicationController
  def index
    @owned_prayer_slots = PrayerSlot.where(user: current_user).order('due ASC')
  end

  def add
    if !user_signed_in?
      render json: { message: 'Please sign in to pick time slots.', toastrType: 'warning' }
    else
      due = Time.at(params[:time_i].to_i).utc
      formatted_due = "#{Time.zone.at(due).strftime("%b %d @%l:%M %P")} #{TimeZonePresenter.short_name(Time.zone.now)}"

      existing_slot = PrayerSlot.find_by(user: current_user, due: due)
      if existing_slot.present?
        existing_slot.delete
        message = "Removed<br />#{formatted_due}"
        toastr_type = 'info'
      else
        PrayerSlot.create!(user: current_user, due: due)
        message = "Added<br />#{formatted_due}"
        toastr_type = 'success'
      end

      render json: { message: message, toastrType: toastr_type }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title= content_for?(:title) ? yield(:title) : "626 Mandate"

    = stylesheet_link_tag    "application"
    = stylesheet_link_tag href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = javascript_include_tag href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
    = stylesheet_link_tag    "toastr.css"
    = csrf_meta_tags

  body
    = yield :javascript
    / toastr js notifications
    = render 'shared/toastr', flash: flash

    .topbar
      .row
        .large-12.columns
          nav.top-bar(data-topbar role="navigation")
            ul.title-area
              li.name
                h1
                  a(href="/" style="padding-left: 0") 626 Mandate
              li.toggle-topbar
                a(href="#")
                  span Menu
            / don't show menu when users are logging in
            section.top-bar-section
              <!-- Right Nav Section -->
              ul.right
                - if user_signed_in?
                  li= link_to 'Calendar', '/'
                  li= link_to 'My Prayer Times', prayer_slots_path
                  li= link_to 'Time Zone', time_zone_path

                  li.has-form(style="padding-right: 0")
                    = link_to('Logout', destroy_user_session_path, class: 'button success')
                - else
                  li
                    strong
                      = link_to("Sign In", new_user_session_path, class: 'button success')

    .row
      .large-12.columns
        img(src=image_url('626banner.jpg'))
        = yield

    /javascript:
      $(document).ready(function() {
        $("table tr td").click(function(event) {
          var slot = $(this).data('slot');
          console.log(slot);
        });
      });

app/views/pages/_time_slots.html.slim
ruby:
  # some constants...move these somewhere more appropriate
  time_format = '%l:%M%P'
  calendar_start_date = calendar_start_date + 12.hours if am_pm == 'PM'

table.time-slots
  thead
    th: h4: strong= am_pm
    - 7.times do |i|
      - date = calendar_start_date + i.day
      th= "#{date.strftime('%a')} #{date.day}"
  tbody
    - 24.times do |i|
      - time = calendar_start_date + (i * 30).minutes
      tr
        td= time.strftime(time_format)[0..-2]
        - 7.times do |i|
          ruby:
            adjusted_time_i = (time + i.day).to_i
            count = prayer_slot_counts[adjusted_time_i] || 0
            empty = count == 0 ? 'empty' : ''
            owned = owned_prayer_slots[adjusted_time_i] == true ? 'owned' : ''
            inactive = inactive_prayer_slots[adjusted_time_i] == true ? 'inactive' : ''
            class_name = [empty, owned, inactive].join(' ')
          td{class=class_name data-slot=adjusted_time_i}
            - next if count == 0
            = count

app/views/pages/time_zone.html.slim
h2 My Time Zone
h4= current_user.email

ruby:
  time_zones = [
    ['Pacific Time (US & Canada)', 'Pacific Time (US & Canada)'],
    ['Eastern Time (US & Canada)', 'Eastern Time (US & Canada)'],
    ['Beijing', 'Beijing'],
    ['Hanoi', 'Hanoi']
  ]

.row
  .large-4.columns
    = form_tag(change_time_zone_path, method: 'post') do
      = select_tag('time_zone',
        options_for_select(time_zones, selected: Time.zone.name),
        onchange: 'this.form.submit()')

app/views/pages/welcome.html.slim
= content_for :javascript do
  = javascript_include_tag 'time_slots'

ruby:
  # some constants...move these somewhere more appropriate
  time_format = '%l:%M'

p
.alert-box.secondary(data-alert)
  h3 Instructions
  p
    '626 Mandate is a 24 hour prayer movement that comes directly from Isaiah 62:6 (NIV),
    '“I have posted watchmen on your walls, O Jerusalem; they will never be silent day or
    'night. You who call on the LORD, give yourselves no rest.” 
  p
    'After logging in, please click on time slots to commit to pray for that 30 minute
    'block.
  p
    'For prayer topics, visit
    = link_to 'this link', 'http://churchofsouthland.com/prayer/', target: '_blank'
    '.

    /You will receive an email notification prior to your time slot to remind you
    /to pray.  

.row
  .large-6.columns
    .row
      .large-8.columns
        h2
          - if @prev_link
            a(href="#{root_path}")
              i.fa.fa-arrow-circle-left
            |&nbsp;

          = @calendar_start_date.strftime('%B %e')
          |&nbsp;
          |-
          |&nbsp;
          = (@calendar_start_date + 6.days).day

          / HACK: hard code this for now
          - if @next_link
            |&nbsp;
            a(href="#{root_path(c: 1)}")
              i.fa.fa-arrow-circle-right
      .large-4.columns.text-right
        h2= link_to TimeZonePresenter.short_name(Time.zone.now), time_zone_path
.row
  .large-6.columns
    = render 'time_slots',
      am_pm: 'AM',
      calendar_start_date: @calendar_start_date,
      prayer_slot_counts: @prayer_slot_counts,
      owned_prayer_slots: @owned_prayer_slots,
      inactive_prayer_slots: @inactive_prayer_slots
  .large-6.columns
    = render 'time_slots',
      am_pm: 'PM',
      calendar_start_date: @calendar_start_date,
      prayer_slot_counts: @prayer_slot_counts,
      owned_prayer_slots: @owned_prayer_slots,
      inactive_prayer_slots: @inactive_prayer_slots

app/views/prayer_slots/index.html.slim
ruby:
  # some constants...move these somewhere more appropriate
  time_format = '%l:%M %P'

.row
  .large-12.columns
    h2 My Prayer Times - #{TimeZonePresenter.short_name(Time.zone.now)}
    h4= current_user.email

    ul
      - @owned_prayer_slots.each do |slot|
        li(class=(Time.current > slot.due ? 'strikethrough' : ''))
          = slot.due.strftime("%A, %B %e, #{time_format}")

app/views/shared/_toastr.html.slim
javascript:
  toastr.options.timeOut = 10000;
  toastr.options.extendedTimeOut = 300;
  toastr.options.progressBar = true;
  toastr.options.positionClass = "toast-top-left";
- if flash.any?
  - flash.each do |k,v|
    javascript:
      var noticeType;
      if(#{raw(ApplicationController::TOASTR_TYPES.map(&:to_s))}.indexOf("#{k}") == -1) {
        // default to 'success'
        noticeType = 'success';
      } else if('#{k}' == 'info') {
        // use 'success' color instead of 'info' to differentiate from button color
        noticeType = 'success';
      } else {
        noticeType = "#{k}";
      }
      toastr[noticeType]("#{v}");

app/views/user_notifier/send_daily_notification.html.slim
doctype html
html
  head
    meta(content='text/html; charset=UTF-8' http-equiv='Content-Type')
  body
    'Your prayer time is coming up: #{@due_text}.